// app/portfolio/page.tsx
import { BlogPosts } from "app/components/posts";

export const metadata = {
  title: "Blog",
  description: "Read my blog.",
};

export default function Page() {
  return (
    <section>
      <h1 className="font-bold title text-4xl mb-1 tracking-tighter">
        Work Experience - Elaborated
      </h1>
      <hr />
      <BlogPosts />
    </section>
  );
}

// src/routes/[locale]/portfolio/+page.svelte
<script lang="ts">
	import PostSection from '$lib/components/PostSection.svelte';
	import { t } from '$lib/i18n';
	import type { PageData } from './$types';

	interface Props {
		data: PageData;
	}

	let { data }: Props = $props();
</script>

<section>
	<h1 class="font-bold title text-4xl mb-1 tracking-tighter">
		{t(data.messages, 'PortfolioPage', 'projects.value')}
	</h1>
	<hr />
	<PostSection posts={data.projects} />

	<h1 class="font-bold title text-4xl mb-1 mt-12 tracking-tighter">
		{t(data.messages, 'PortfolioPage', 'personal.value')}
	</h1>
	<hr />
	<PostSection posts={data.personal} />
</section>
